version: '3'
services: 
    db-lab2:
        build: '.'
        volumes:
            - .:/usr/app
        environment:
            PORT:   3000
            PGHOST: postgres
            PGUSER: veetaha
            PGPORT: 5432
            DB_PASSWORD: pgpassword
            PASSWORD_SALT: dev-challenge-salt
            DB_DB: pgdb
        ports:
            - 3000:3000
        links: 
            - postgres
        depends_on: 
            - postgres
    postgres:
        image: postgres
        restart: always
        hostname: postgres
        stdin_open: false
        tty: false
        ports: 
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: pgpassword
            POSTGRES_USER: pguser
            POSTGRES_DB:   pgdb
